model: nips19.iccv19.model.TrainModel
iterator: nips19.iccv19.model.Trainer
triplet_path: triplet_checkpoints/deepfashion/triplet_reid.ckpt-99000

dataset: nips19.data.data.StochasticPairs
data_root: data/deepfashion
data_csv: data/deepfashion/filtered_train.csv
data_avoid_identity: False
data_flip: True

batch_size: 1
spatial_size: 128

lr: 2.0e-4
lr_decay_begin: 250000
lr_decay_end: 500000
#log_freq: 250
log_freq: 1
ckpt_freq: 50000
num_steps: 500001
gpu_mem_growth: True
gpu_mem_fraction: 0.333