model: nips19.SB_model28b.model.TrainModel
iterator: nips19.eval.eval.Evaluator
triplet_path: triplet_checkpoints/deepfashion/triplet_reid.ckpt-99000

dataset: nips19.final_eval.eval.MatrixData
data_root: data/deepfashion
data_row_csv: data/deepfashion/eval_test_50.csv
data_col_csv: data/deepfashion/eval_test_50.csv

batch_size: 7
n_data_processes: 2
eval_forever: False
eval_all: True

spatial_size: 256
generated_key: t_generated
vis0_key: generated
vis1_key: t_mask
transpose: True

#
#
#conditional_transfer:
#  t_list: [0, 1, 0, 1, 0, 1]