model: nips19.SB_model28b.model.TrainModel
iterator: nips19.final_eval.eval.TableEvaluator
triplet_path: triplet_checkpoints/deepfashion/triplet_reid.ckpt-99000

dataset: nips19.final_eval.eval.TableData
data_root: data/exercise_data/exercise_dataset
data_col_csv: data/exercise_data/eval_test_exercise.csv

batch_size: 5
n_data_processes: 2
eval_forever: False
eval_all: True

spatial_size: 256
header_key: view0
value_keys: [view0_mask_rgb]
