model: nips19.SB_model48i.model.TrainModel
iterator: nips19.SB_model48i.model.Trainer

dataset: src.data.data.AugmentedPair2
data_root: data/pennaction
data_csv: data/pennaction/cropped_jumping_jacks_pullup_train.csv

data_avoid_identity: False
data_augment_appearance: False
data_augment_shape: False
data_flip_h: False
data_flip_v: False
data_rotate: False
data_csv_columns : ["character_id", "relative_file_path_"]
data_csv_has_header : True


batch_size: 8
spatial_size: 128
patch_size: 32


lr: 2.0e-4
lr_decay_begin: 1000000
lr_decay_end:   1000001
log_freq:     250
ckpt_freq:   10000
num_steps:  1000000


kl_weight:
  start: 0
  end: 1
  start_value: 1.0
  end_value:   1.0


mumford_sha_alpha:
  var_type: staircase
  options:
    start:        65000
    start_value:  1.0
    step_size:    10000
    stair_factor: 10
    clip_min:     1.0e-2
    clip_max:     1.0e-2


MI:
  mi_target: 1.5
  mi_slack:  0.05
  loa_init:  0.0
  loa_lr:    4.0
  loa_adaptive: True
  lor_init:  0.0
  lor_lr:    0.05
  lor_min:   -3.0
  lor_max:   7.5
  lor_adaptive: True


mumford_sha_lambda:
  var_type: staircase
  options:
    start:        65000
    start_value:  1.0
    step_size:    5000
    stair_factor: 10
    clip_min:     1.0
    clip_max:     1.0


variance_weight:
  var_type: staircase
  options:
    start:        31000
    start_value:  50
    step_size:    30000
    stair_factor: 2
    clip_min:     1 # normally 1
    clip_max:     1 # normally 6400 


prior_gmrf_weight:
  var_type: staircase
  options:
    start:        100000
    start_value:  1.0e-2
    step_size:    20000
    stair_factor: 3.14
    clip_min:     1.0e-3
    clip_max:     1.0e-3


patch_loss_weight:
  var_type: staircase
  options:
    start:        100000
    start_value:  1.0e-2
    step_size:    20000
    stair_factor: 3.14
    clip_min:     1.0e-4
    clip_max:     1.0e-4



prior_mumford_sha_weight:
  var_type: staircase
  options:
    start:        81000
    start_value:  1.0e+0
    step_size:    20000
    stair_factor: 10
    clip_min:     1.0e-5
    clip_max:     1.0e-5


weakly_superv_loss_weight_p:
  var_type: linear
  options:
    start:          60000
    end:            80000
    start_value:       1
    end_value:      1.0e+3
    clip_min:       1.0
    clip_max:       1.0
    # start_step :    100000
    # period_duration_in_steps: 30000


n_parts : 25
gamma : 10


restore_exclude : []

z0_size : 256 # pi encoding length, has to be size divisible by n_parts
local_app_size : 64

test_mode: False
adversarial_regularization: True
variational_regularization: True
entropy_func: entropy


encoder0:
  config : [32, 64, 128, 128, 256, 256]
  extra_resnets : 4
  activation : "leaky_relu"
  coords: True

final_hour:
  config : [32, 64]
  extra_resnets : 0
  upsample_method: "linear" # TODO: linear or subpixel?
  activation: "leaky_relu"
  coords: False

encoder1 :
  config : [32, 64, 128, 128, 256, 256]
  extra_resnets : 4
  activation: "leaky_relu"
  coords: True

dv:
  config : [16, 32, 32, 128, 128, 256]
  upsample_config: ["linear", "linear", "linear", "linear", "linear"]
  activation: "leaky_relu"
  coords: True

d_single:
  config : [16, 32, 32, 128, 128, 256]
  upsample_config: ["linear", "linear", "linear", "linear", "linear"]
  activation: "leaky_relu"
  coords: True


discriminator:
  activation: "leaky_relu"
  coords: False





use_tps: False
tps_parameters: # adapted from https://github.com/CompVis/unsupervised-disentangling
  scal: 0.8
  tps_scal: 0.15
  rot_scal: 0.2
  off_scal: 0.2
  scal_var: 0.1
  augm_scal: 1.0